apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-delay-bind-claim
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: delay-bind
